### ISSUE TITLE
Syntax highlighter errors with `matCellDef` from Material Angular Table

### ISSUE THREAD

**Issue by finnmerlett** [dannymcgee/vscode-ng-html#2]
There is a syntax used in the Material Angular library, on the mat-table component, where there is an angular directory `*matCellDef` that takes a string-quoted command of "let iteratedItem": `*matCellDef="let user"`. This is correct syntax, but the highlighter obviously expects it to be in the form let x of y, and so colours most of the following code in red. Supporting this is the fact that if the quoted strings are changed to `"let user of tempFormattingFix"`, the buggy colouring dissapears.
![image](https://user-images.githubusercontent.com/49064567/70458013-2160ab00-1aa9-11ea-88e1-c0c2c6d5332b.png)
![image](https://user-images.githubusercontent.com/49064567/70458542-270ac080-1aaa-11ea-8345-243bd96b8126.png)

**Comment by dannymcgee** [comment]
@finnmerlett Thanks for the heads up! Does it fix the highlighting (_without_ breaking your code) if you put a semicolon after `user`, like `<td mat-cell *matCellDef="let user;">`? This extension actually isn't super sophisticated — it just tells VS Code to parse anything inside an Angular attribute as if it were JavaScript. So I've noticed that when you try to use a fragment like this one that wouldn't qualify as a complete JS expression, the JS grammar parser gets confused and everything afterwards breaks. Adding a semicolon has fixed that issue for me under similar circumstances. Not really an ideal solution but might be a useful workaround until I get the time to try and find a proper fix.

**Comment by dannymcgee** [comment]
@finnmerlett I tested out the Material table locally and it looks like it doesn't break anything to add a semicolon to the end of the `*matCellDef` value, so that's what I'd recommend as a workaround for now. Thanks again for reporting this!

**Comment by dannymcgee** [comment]
I went ahead and added a new issue for this with more detailed information [here](https://github.com/dannymcgee/vscode-ng-html/issues/4)

**Comment by finnmerlett** [comment]
Thanks for looking into this, I will apply the tip you suggested!
