### ISSUE TITLE
how to enable this extension?

### ISSUE THREAD

**Issue by mhamri** [dannymcgee/vscode-ng-html#5]
I can't find it in the theme color, nothing mentioned in the readme.md, the code formating is not applied by default. so how to enable this?

**Comment by dannymcgee** [comment]
With the extension installed (and not disabled), it should work automatically. You can install and enable/disable it [the same way you would with any other extension](https://code.visualstudio.com/docs/editor/extension-gallery).

I'm not sure what you mean by "can't find it in the theme color" — this extension replaces the TextMate grammar definition for HTML files, it's not a theme. Whatever theme you use will color the code according to its own rules for the grammar scopes, and all of the grammar scopes used by this extension are default (i.e. not unique to this extension), so it should work with whatever theme you'd like. The screenshots in the readme show what it should look like with the default VS Code Dark theme, [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme), and my own theme, [Summer Vacation](https://marketplace.visualstudio.com/items?itemName=dannymcgee.summer-vacation-theme).

- When you open your Extensions panel, do you see **Angular HTML Syntax** in the list under Enabled? If not, is it under Disabled?
- Do you have any other extensions installed which may have overridden the default HTML grammar?
- When you have an HTML file open, does it say "HTML" in the status bar at the bottom right of the screen? If not, try clicking on the Language Mode and changing it to Auto Detect.

**Comment by mhamri** [comment]
sorry, look like I misunderstood the extension behavior. closing it.
